import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{BookOpen,Users,GraduationCap,School,Plus,LogOut,PlayCircle,ChevronRight,LayoutDashboard,Video,Settings,UserPlus,Copy,CheckCircle2,ArrowLeft,Search,Clapperboard}from'lucide-react';
import Studio from'./studio.jsx';
import'./styles.css';
const KEY='hocngaynao-portal-v1';
const seed={role:'teacher',user:{name:'Cô Trang',email:'teacher@example.com'},classes:[{id:'class-1',name:'Lịch sử 10 – K10A',code:'LS10K10A',teacher:'Cô Trang',students:12,course:'Lịch sử 10'},{id:'class-2',name:'Toán 9 – K9A',code:'TOAN9K9A',teacher:'Cô Trang',students:28,course:'Toán 9'}],courses:[{id:'course-1',name:'Lịch sử 10',description:'Chương trình học và bài giảng trực tuyến',lessons:[{id:'l1',title:'Bài 1 – Nhập môn lịch sử',duration:'18 phút',video:'https://www.youtube.com/embed/dQw4w9WgXcQ'},{id:'l2',title:'Bài 2 – Các cuộc cách mạng công nghiệp',duration:'32 phút',video:''},{id:'l3',title:'Bài 3 – Việt Nam thời cận đại',duration:'25 phút',video:''}]},{id:'course-2',name:'Toán 9',description:'Đại số và hình học',lessons:[{id:'l4',title:'Bài 1 – Căn bậc hai',duration:'24 phút',video:''},{id:'l5',title:'Bài 2 – Căn thức',duration:'31 phút',video:''}]}],enrollments:[{student:'Nguyễn Minh',classId:'class-1',progress:35},{student:'Lê An',classId:'class-1',progress:72}]};
function load(){try{return JSON.parse(localStorage.getItem(KEY))||seed}catch{return seed}}function save(d){localStorage.setItem(KEY,JSON.stringify(d))}
function App(){const[data,setData]=useState(load),[page,setPage]=useState('dashboard'),[selectedClass,setSelectedClass]=useState(null),[selectedCourse,setSelectedCourse]=useState(null),[studio,setStudio]=useState(false),[joinCode,setJoinCode]=useState(''),[notice,setNotice]=useState('');useEffect(()=>save(data),[data]);const isStudent=data.role==='student';const cls=selectedClass?data.classes.find(x=>x.id===selectedClass):null;const course=selectedCourse?data.courses.find(x=>x.id===selectedCourse):null;const nav=(p)=>{setPage(p);setSelectedClass(null);setSelectedCourse(null)};
function createClass(){const name=prompt('Tên lớp học?','Lịch sử 10 – K10B');if(!name)return;const code=name.replace(/[^A-Z0-9À-ỹ]/gi,'').slice(0,5).toUpperCase()+Math.floor(100+Math.random()*900);setData({...data,classes:[...data.classes,{id:crypto.randomUUID(),name,code,teacher:data.user.name,students:0,course:data.courses[0]?.name||'Khóa học mới'}]});setNotice(`Đã tạo lớp. Mã tham gia: ${code}`)}
function joinClass(){const found=data.classes.find(c=>c.code.toUpperCase()===joinCode.trim().toUpperCase());if(!found){setNotice('Không tìm thấy mã lớp');return}setNotice(`Đã tham gia ${found.name}`);setJoinCode('');setPage('classes')}
function openCourse(c){setSelectedCourse(c.id);setPage('course')}
if(studio)return <Studio onBack={()=>setStudio(false)}/>;
return <div className="portal"><header className="portalHeader"><div className="portalBrand"><div className="portalLogo">HN</div><div><b>Học Ngày Nào</b><span>Nền tảng học online</span></div></div><nav><button className={page==='dashboard'?'navActive':''} onClick={()=>nav('dashboard')}><LayoutDashboard/> Tổng quan</button><button className={page==='classes'?'navActive':''} onClick={()=>nav('classes')}><Users/> {isStudent?'Lớp của tôi':'Lớp học'}</button><button className={page==='courses'?'navActive':''} onClick={()=>nav('courses')}><BookOpen/> Khóa học</button>{!isStudent&&<button onClick={()=>setStudio(true)}><Clapperboard/> Teaching Studio</button>}</nav><div className="account"><span>{data.user.name}</span><button title="Đổi vai trò" onClick={()=>setData({...data,role:isStudent?'teacher':'student'})}><GraduationCap/></button><button onClick={()=>setData({...data,user:{name:'Khách',email:''}})}><LogOut/></button></div></header><main className="portalMain">{notice&&<div className="notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}{page==='dashboard'&&<Dashboard data={data} isStudent={isStudent} onCourse={openCourse} onClass={(id)=>{setSelectedClass(id);setPage('class')}} onCreate={createClass} onStudio={()=>setStudio(true)} onJoin={joinClass} joinCode={joinCode} setJoinCode={setJoinCode}/>} {page==='classes'&&<Classes data={data} isStudent={isStudent} onClass={(id)=>{setSelectedClass(id);setPage('class')}} onCreate={createClass} onJoin={joinClass} joinCode={joinCode} setJoinCode={setJoinCode}/>} {page==='courses'&&<Courses data={data} onCourse={openCourse}/>} {page==='class'&&cls&&<ClassPage cls={cls} data={data} isStudent={isStudent} onBack={()=>nav('classes')} onCourse={(name)=>{const c=data.courses.find(x=>x.name===name);if(c)openCourse(c)}}/>} {page==='course'&&course&&<CoursePage course={course} data={data} isStudent={isStudent} onBack={()=>nav('courses')}/>} </main></div>}
function Dashboard({data,isStudent,onCourse,onClass,onCreate,onStudio,onJoin,joinCode,setJoinCode}){return <div className="dash"><section className="hero"><div><p className="eyebrow">{isStudent?'KHU HỌC TẬP':'KHU GIẢNG DẠY'}</p><h1>{isStudent?'Học hôm nay, tiến bộ mỗi ngày.':'Tạo lớp, tạo bài giảng và giao bài.'}</h1><p>{isStudent?'Vào lớp để tiếp tục những bài đang học.':'Quản lý lớp học và mở Teaching Studio để quay bài giảng ngay trên web.'}</p></div>{!isStudent&&<button className="primary big" onClick={onStudio}><Video/> Mở Teaching Studio</button>}</section><div className="stats"><Stat icon={<School/>} label={isStudent?'Lớp đã tham gia':'Lớp học'} value={data.classes.length}/><Stat icon={<BookOpen/>} label="Khóa học" value={data.courses.length}/><Stat icon={<GraduationCap/>} label={isStudent?'Bài đã học':'Học viên'} value={isStudent?'4':data.enrollments.length}/></div><div className="grid2"><section className="card"><div className="cardHead"><h2>{isStudent?'Lớp của tôi':'Lớp đang quản lý'}</h2><button onClick={onClass&&(()=>{})}>Xem tất cả</button></div>{data.classes.slice(0,3).map(c=><ClassCard key={c.id} c={c} onClick={()=>onClass(c.id)} isStudent={isStudent}/>)}</section><section className="card"><div className="cardHead"><h2>{isStudent?'Khóa học đề xuất':'Khóa học'}</h2></div>{data.courses.map(c=><CourseRow key={c.id} c={c} onClick={()=>onCourse(c)}/>)}</section></div>{isStudent&&<section className="joinBox"><div><b>Tham gia lớp bằng mã</b><span>Nhập mã giáo viên gửi cho bạn.</span></div><div className="joinForm"><input value={joinCode} onChange={e=>setJoinCode(e.target.value)} placeholder="VD: LS10K10A"/><button className="primary" onClick={onJoin}>Tham gia</button></div></section>}</div>}
const Stat=({icon,label,value})=><div className="stat"><div>{icon}</div><span>{label}</span><b>{value}</b></div>;
function ClassCard({c,onClick,isStudent}){return <button className="classCard" onClick={onClick}><div className="classIcon"><School/></div><div><b>{c.name}</b><span>{c.course} • {isStudent?'Đang học':`${c.students} học viên`}</span></div><ChevronRight/></button>};
function CourseRow({c,onClick}){return <button className="courseRow" onClick={onClick}><div className="courseCover"><BookOpen/></div><div><b>{c.name}</b><span>{c.lessons.length} bài học • {c.description}</span></div><ChevronRight/></button>}
function Classes({data,isStudent,onClass,onCreate,onJoin,joinCode,setJoinCode}){return <div className="page"><div className="pageTitle"><div><p className="eyebrow">{isStudent?'HỌC TẬP':'QUẢN LÝ'}</p><h1>{isStudent?'Lớp của tôi':'Lớp học'}</h1><p>{isStudent?'Các lớp bạn đã tham gia.':'Tạo lớp và gửi mã tham gia cho học viên.'}</p></div>{isStudent?<div className="joinForm"><input value={joinCode} onChange={e=>setJoinCode(e.target.value)} placeholder="Mã lớp"/><button className="primary" onClick={onJoin}><UserPlus/> Tham gia</button></div>:<button className="primary" onClick={onCreate}><Plus/> Tạo lớp</button>}</div><div className="classGrid">{data.classes.map(c=><ClassCard key={c.id} c={c} onClick={()=>onClass(c.id)} isStudent={isStudent}/>)}</div></div>}
function Courses({data,onCourse}){return <div className="page"><div className="pageTitle"><div><p className="eyebrow">THƯ VIỆN</p><h1>Khóa học</h1><p>Toàn bộ khóa học và bài giảng.</p></div></div><div className="courseGrid">{data.courses.map(c=><button className="courseCard" key={c.id} onClick={()=>onCourse(c)}><div className="courseBanner"><BookOpen/></div><div className="courseBody"><b>{c.name}</b><span>{c.description}</span><small>{c.lessons.length} bài học</small></div></button>)}</div></div>}
function ClassPage({cls,data,isStudent,onBack,onCourse}){return <div className="page"><button className="backLink" onClick={onBack}><ArrowLeft/> Quay lại</button><div className="detailHero"><div className="classIcon large"><School/></div><div><p className="eyebrow">LỚP HỌC</p><h1>{cls.name}</h1><p>{cls.course} • Giáo viên: {cls.teacher}</p></div><div className="classCode"><span>MÃ THAM GIA</span><b>{cls.code}</b><button onClick={()=>navigator.clipboard?.writeText(cls.code)}><Copy/> Sao chép</button></div></div><section className="card"><div className="cardHead"><h2>{isStudent?'Nội dung học':'Nội dung lớp'}</h2><span>{isStudent?'Chọn bài để học':'Học viên: '+cls.students}</span></div><button className="courseRow" onClick={()=>onCourse(cls.course)}><div className="courseCover"><BookOpen/></div><div><b>{cls.course}</b><span>Mở toàn bộ chương trình và video bài giảng</span></div><ChevronRight/></button></section></div>}
function CoursePage({course,isStudent,onBack}){const[lesson,setLesson]=useState(course.lessons[0]);return <div className="page"><button className="backLink" onClick={onBack}><ArrowLeft/> Quay lại</button><div className="courseDetail"><div className="lessonList"><p className="eyebrow">KHÓA HỌC</p><h1>{course.name}</h1><p>{course.description}</p>{course.lessons.map((l,i)=><button key={l.id} className={lesson.id===l.id?'lessonActive':''} onClick={()=>setLesson(l)}><span>{String(i+1).padStart(2,'0')}</span><div><b>{l.title}</b><small>{l.duration}</small></div><ChevronRight/></button>)}</div><div className="lessonViewer"><div className="videoBox">{lesson.video?<iframe title={lesson.title} src={lesson.video} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/>:<div><PlayCircle size={56}/><b>Video chưa được đăng</b><span>Giáo viên đang hoàn thiện bài giảng.</span></div>}</div><h2>{lesson.title}</h2><div className="lessonMeta"><CheckCircle2/> {isStudent?'Đánh dấu hoàn thành sau khi học':'Bài giảng'}</div></div></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
